- module/model-elasticsearch/src/source.ts
> added postLoad for updatePartialByQuery

- docs/ACTIVE.md
- docs/COMPLETED.md
- module/model-elasticsearch/test/text.ts
- module/schema/src/bind-util.ts
- module/schema/src/decorator/field.ts
- module/schema/test/binding.ts
- module/schema/test/models/address.ts
- module/schema/test/models/binding.ts
- module/schema/test/models/validation.ts
- module/schema/test/validation.ts
...
Bringing in support for regex as strings in schema binding, and text fields supporting arrays
> Supporting regex binding and text arrays

- bin/dev-init/finalize.ts
- module/base/bin/bootstrap.js
- module/base/bin/travetto-cli-boot.js
- module/base/src/bootstrap/env.js
- module/base/src/shutdown.ts
- module/base/src/watch.ts
- module/base/test/watch.ts
- module/cli/bin/travetto.js
- module/cli/src/util.js
- module/compiler/src/compiler.ts
- module/di/bin/travetto-cli-run.js
- module/di/bin/travetto-find-apps.js
- module/exec/src/child.ts
- module/exec/src/execution.ts
- module/exec/src/pool/pool.ts
- module/log/e2e/src/simple.ts
- module/test/bin/init.js
- module/test/bin/travetto-cli-test.js
- module/test/src/runner/communication.ts
...
Reworking ability to init scripts, as well as simple logging.  Additionally, fixed test module unloading behavior to prevent missed Shutdown operations.
> Test resolution

- module/schema/src/validate/types.ts
- module/schema/src/validate/validator.ts
> made Validator decorator async-friendly

- module/base/src/util.ts
- module/base/test/util.ts
- module/rest-session/src/service.ts
- module/worker/src/input/iterator.ts
- module/worker/src/input/types.ts
- module/worker/src/pool.ts
Enabling async iterators for worker pools, as well as fixing issue with dates in object util merge
> Supporting async worker pool operations

- module/model-elasticsearch/src/source.ts
> updateAllByQuery for elastic search model fixing syntax issues

- module/model-elasticsearch/src/source.ts
> refresh on elasticsearch delete

- docs/tasking/ACTIVE.md
- docs/tasking/COMPLETED.md
- docs/tasking/PIPELINE.md
- module/model-elasticsearch/src/source.ts
- module/model-elasticsearch/src/util.ts
- module/model-elasticsearch/test/simple.ts
- module/model-elasticsearch/test/util.ts
- module/model-mongo/src/source.ts
- module/model-sql/src/source.ts
- module/model-sql/src/util.ts
- module/model-sql/support/phase.test.ts
- module/model/index.ts
- module/model/src/util/model.ts
- module/rest-express/src/app.ts
- module/rest-fastify/src/app.ts
- module/rest-koa/src/app.ts
- module/rest/src/config.ts
...
Fixes: 
* #47 entirely
* Issue with SQL Model service and caching of incorrect field path when using polymorphism
* Partial update in elasticsearch on empty objects. #48 
* Exposes a new field in rest app to specify the bindAddress
* SQL tests now default to running postgres as mysql isn't the greatest.
> Minor fixes for patch release

- docs/design/MODEL.md
- docs/tasking/ACTIVE.md
- docs/tasking/COMPLETED.md
- module/model-elasticsearch/package.json
- module/model-elasticsearch/src/config.ts
- module/model-elasticsearch/src/source.ts
- module/model-elasticsearch/test/resources/application.yml
- module/net/src/request.ts
- module/net/src/util.ts
Upgrading to new elasticsearch library
> 1.0.0 model es upgrade

- module/model-elasticsearch/src/config.ts
- module/model-elasticsearch/src/source.ts
- module/rest/src/interceptor/cors.ts
> export rest cors origin

- module/app/tsconfig.json
- module/boot/package.json
- module/boot/src-ts/env.ts
- module/boot/src-ts/transpile.ts
- module/boot/tsconfig.json
- module/cli/bin/travetto.js
- module/cli/package.json
- module/doc/tsconfig.json
- module/generator-app/templates/todo/test/tsconfig.json
- module/schema/test/rest.ts
- module/transformer/alt/recursive/tsconfig.json
- module/transformer/alt/upper/tsconfig.json
- module/transformer/test/lib/util.ts
- module/transformer/test/recursive.ts
> Resolving boot issues

- module/rest-client/src/provider/angular.ts
- module/rest-client/src/provider/base.ts
- module/rest-client/src/provider/shared/angular-service.ts
- module/rest-client/src/provider/shared/types.ts
> feat(rest-client): Polishing angular generator

- module/cli/DOC.html
- module/cli/README.md
- module/cli/src/decorators.ts
- module/cli/src/module.ts
- module/cli/src/registry.ts
- module/cli/src/types.ts
- module/cli/src/util.ts
- module/model/support/cli.model_export.ts
- module/model/support/cli.model_install.ts
- module/openapi/support/cli.openapi_spec.ts
- module/pack/support/cli.pack.ts
- module/pack/support/cli.pack_docker.ts
- module/pack/support/cli.pack_zip.ts
- module/rest-aws-lambda/support/cli.pack_lambda.ts
- module/rest-client/support/cli.rest_client.ts
- module/rest/DOC.html
- module/rest/README.md
- module/rest/support/cli.run_rest.ts
- related/travetto.github.io/src/app/documentation/gen/cli/cli.component.html
- related/travetto.github.io/src/app/documentation/gen/rest/rest.component.html
> feat(cli): Allow cli to specify runtime module behavior

- module/auth-rest/test/verifier.ts
- module/compiler/src/compiler.ts
- module/compiler/src/state.ts
- module/compiler/src/watch.ts
- module/compiler/support/entry.trvc.ts
- module/compiler/support/log.ts
- module/compiler/support/server/runner.ts
- module/compiler/support/server/server.ts
- module/compiler/support/util.ts
- module/email/src/resource.ts
- module/manifest/src/manifest-index.ts
- module/manifest/src/util.ts
> feat(compiler): Cleaning up compiler behavior, edge cases

- module/cli/bin/trv.js
- module/compiler/bin/trvc.js
- module/compiler/src/compiler.ts
- module/compiler/src/event.ts
- module/compiler/src/watch.ts
- module/compiler/support/entry.compiler.ts
- module/compiler/support/entry.trvc.ts
- module/compiler/support/log.ts
- module/compiler/support/server/client.ts
- module/compiler/support/server/runner.ts
- module/compiler/support/server/server.ts
- module/compiler/support/types.ts
> Server restart cleanup

- module/cli/src/util.ts
- module/email-inky/src/wrapper.ts
- module/manifest/src/dependencies.ts
- module/manifest/src/types/manifest.ts
- module/manifest/src/types/package.ts
- module/manifest/src/util.ts
- module/rest/doc-exec/package.json
- module/scaffold/package.json
- notes/design/2024/MODULE_INDEX.md
> feat(manifest): Final iteration on dependency resolution

- module/log/DOC.html
- module/log/README.md
- module/log/__index__.ts
- module/log/src/formatter/google.ts
- module/log/src/formatter/json.ts
- module/log/src/formatter/line.ts
- module/log/src/formatter/util.ts
- module/log/src/service.ts
- module/log/src/types.ts
- module/log/test/logger.ts
- module/rest/src/util/net.ts
- related/travetto.github.io/src/app/documentation/gen/log/log.component.html
- related/vscode-plugin/src/core/run.ts
> feat(log): Removing context as a common concept

- module/base/src/shutdown.ts
- module/base/src/util.ts
- module/base/src/watch.ts
- module/command/src/util.ts
- module/compiler/src/compiler.ts
- module/compiler/support/server/client.ts
- module/compiler/support/server/process-handle.ts
- module/compiler/support/server/server.ts
- module/compiler/support/util.ts
- module/model-sqlite/src/connection.ts
- module/model/src/internal/service/expiry.ts
- module/terminal/src/terminal.ts
- module/test/src/execute/executor.ts
- module/test/src/execute/util.ts
- module/test/src/trv.d.ts
- module/test/src/worker/child.ts
- module/test/support/bin/run.ts
- module/worker/src/pool.ts
- module/worker/src/support/barrier.ts
- module/worker/src/support/timeout.ts
- related/vscode-plugin/src/core/workspace.ts
- related/vscode-plugin/src/feature/compiler/watch/main.ts
> chore(common): Making timers unreffed where possible

- module/base/src/util.ts
- module/compiler/src/state.ts
- module/compiler/src/util.ts
- module/compiler/src/watch.ts
- module/compiler/support/server/server.ts
- module/compiler/support/util.ts
- module/manifest/src/module.ts
- module/manifest/src/types/manifest.ts
- module/rest-client/src/service.ts
- related/todo-app/DOC.tsx
- related/vscode-plugin/src/feature/compiler/watch/main.ts
> 4.0.0 watch batch

- module/auth-rest/src/service.ts
- module/rest-client/src/config.ts
- module/rest-client/src/provider/angular.ts
- module/rest-client/src/provider/base.ts
- module/rest-client/src/provider/fetch.ts
- module/rest-client/src/provider/rest-rpc.ts
- module/rest-client/src/provider/shared/rest-rpc.d.ts
- module/rest-client/src/provider/shared/rest-rpc.js
- module/rest-client/src/provider/types.ts
- module/rest-client/src/service.ts
- module/rest/src/interceptor/rpc.ts
- module/rest/src/internal/symbol.ts
- module/rest/src/trv.d.ts
- module/rest/src/util/param.ts
- related/todo-app/resources/application.yml
- related/todo-app/resources/ui/index.html
- related/todo-app/resources/ui/js/app.mjs
- related/todo-app/src/auth.config.ts
- related/todo-app/src/auth.ts
- related/todo-app/src/model.ts
- related/todo-app/src/route.ts
feat(rest): Making the rpc client legit
...
> feat(todo): Finalizing rpc patterns

- module/compiler/tsconfig.trv.json
- module/rest-client/src/config.ts
- module/rest-client/src/provider/rest-rpc.ts
- module/rest-client/src/provider/shared/fetch-service.ts
- module/rest-client/src/provider/shared/rest-rpc.d.ts
- module/rest-client/src/provider/shared/rest-rpc.js
- module/rest-client/src/service.ts
- module/rest/src/registry/types.ts
- module/rest/src/registry/visitor.ts
- module/runtime/package.json
- module/transformer/package.json
- package-lock.json
- related/travetto.github.io/package.json
- related/vscode-plugin/package-lock.json
- related/vscode-plugin/package.json
- related/vscode-plugin/src/core/activation.ts
> Rpc overhaul

- module/compiler/src/compiler.ts
- module/compiler/src/state.ts
- module/compiler/src/types.ts
- module/compiler/src/watch.ts
- module/compiler/support/setup.ts
- module/manifest/src/module.ts
- module/rest-client/src/provider/rest-rpc.ts
- module/rest-client/src/provider/shared/rest-rpc.js
> feat(compiler): Break input concept entirely

- module/auth-rest-passport/src/util.ts
- module/model-elasticsearch/src/config.ts
- module/model-elasticsearch/src/index-manager.ts
- module/model-elasticsearch/src/internal/query.ts
- module/model-elasticsearch/src/internal/schema.ts
- module/model-elasticsearch/src/service.ts
- module/model-elasticsearch/test/query.ts
- module/model-mongo/src/config.ts
- module/model-mongo/src/internal/util.ts
- module/model-mongo/src/service.ts
- module/model-mongo/test/query.ts
- module/model-mongo/test/service.ts
- module/model-query/support/test/query.ts
- module/model/src/internal/service/crud.ts
- module/model/src/registry/decorator.ts
- module/model/support/test/crud.ts
- module/runtime/src/function.ts
- module/test/src/assert/util.ts
- related/vscode-plugin/src/feature/log/console/main.ts
> Feat model single ids

- module/test/src/consumer/registry.ts
- module/test/src/consumer/types.ts
- module/test/src/consumer/types/all.ts
- module/test/src/consumer/types/cumulative.ts
- module/test/src/consumer/types/delegating.ts
- module/test/src/consumer/types/event.ts
- module/test/src/consumer/types/exec.ts
- module/test/src/consumer/types/json.ts
- module/test/src/consumer/types/noop.ts
- module/test/src/consumer/types/runnable.ts
- module/test/src/consumer/types/summarizer.ts
- module/test/src/consumer/types/tap-streamed.ts
- module/test/src/consumer/types/tap.ts
- module/test/src/consumer/types/xunit.ts
- module/test/src/execute/runner.ts
- module/test/src/execute/types.ts
- module/test/src/execute/watcher.ts
- module/test/src/worker/child.ts
- module/test/support/bin/run.ts
- module/test/support/bin/types.ts
- module/test/support/cli.test.ts
- module/test/support/cli.test_direct.ts
- module/test/support/cli.test_watch.ts
- package-lock.json
> feat(test): Supporting custom test consumers

- .vscode/launch.json
- module/cli/DOC.html
- module/cli/README.md
- module/email-compiler/src/compiler.ts
- module/manifest/src/context.ts
- module/model-mysql/support/service.mysql.ts
- module/model-s3/src/service.ts
- module/runtime/DOC.html
- module/runtime/README.md
- module/runtime/src/context.ts
- module/runtime/src/env.ts
- module/runtime/test/env.ts
- module/test/src/consumer/registry.ts
- module/test/src/consumer/types/all.ts
- module/test/src/consumer/types/tap-summary.ts
- module/test/src/consumer/types/tap.ts
- module/test/src/worker/standard.ts
- module/test/support/bin/run.ts
- package-lock.json
- package.json
- related/travetto.github.io/src/app/documentation/gen/cli/cli.component.html
- related/travetto.github.io/src/app/documentation/gen/runtime/runtime.component.html
> Various cleanups
